### ISSUE TITLE
jalali to  gregory

### ISSUE THREAD

**Issue by benamm** [alibaba-aero/jalaliday#20]
how i can convert jalali date to gregory ?

**Comment by farnabaz** [comment]
@benamm Sorry for the late response
First create a dayjs instance from jalali date: 
```js
const instance = dayjs(jalaliDateString, { jalali: true })
```
Then change its calendat to gregory: 
```js
const gregory = instance.calendar('gregory').locale('en')
```

**Comment by NotNotMarshall** [comment]
> @benamm Sorry for the late response
> First create a dayjs instance from jalali date:
> 
> ```js
> const instance = dayjs(jalaliDateString, { jalali: true })
> ```
> 
> Then change its calendat to gregory:
> 
> ```js
> const gregory = instance.calendar('gregory').locale('en')
> ```

How to do vice versa?
I mean, Gregory to Khorshidi?

**Comment by farnabaz** [comment]
> How to do vice versa?
```js
const instance = dayjs(gregoryDateString)
const jalali = instance.calendar('jalali').locale('fa')
```
