### ISSUE TITLE
Day.js updates reminder in 1.8.9

### ISSUE THREAD

**Issue by iamkun** [alibaba-aero/jalaliday#6]
Hi there,

Just a quick reminder that there are two changes in 1.8.9 to our developers.

1. Date wrapper `Utils.wrapper` could be overridden in the plugin.

2.  The name of Utiles[*] has been changed to a shorter name in order to reduce the package size.

Cheers.

**Comment by farnabaz** [comment]
Hi,
Thank you very much for your reminder
We should release a new version to support dayjs 1.8.9
