### ISSUE TITLE
U.isUndefined is not a function

### ISSUE THREAD

**Issue by mpourismaiel** [alibaba-aero/jalaliday#9]
According to the following lines I believe Utils object keys aren't really correct. But I don't have any ideas about why this works in the tests.

https://github.com/iamkun/dayjs/blob/dev/src/index.js#L43
https://github.com/iamkun/dayjs/blob/dev/src/utils.js#L45

**Comment by farnabaz** [comment]
This is related to [#6], in the latest release of Dayjs some of the internal function names have been changed.
I'm working to create a new branch and new release to support `Dayjs >= 1.8.9`

**Comment by mpourismaiel** [comment]
I'll close this issue in order to have a cleaner workspace. If you need any help, the master branch of my fork is stable and works with the latest release.
